-- PESSOA --
CREATE TABLE PESSOA(
	CODPESSOA INT, 
	NOMEPESSOA VARCHAR(50), 
	PRIMARY KEY(CODPESSOA)
); 

-- USUARIO --
CREATE TABLE USUARIO(
	CODUSU INT, 
	CPF VARCHAR(20), 
	PRIMARY KEY(CODUSU), 
	FOREIGN KEY(CODUSU) REFERENCES PESSOA(CODPESSOA)
);

-- MOTORISTA --
CREATE TABLE MOTORISTA(
	CODMOTORISTA INT, 
	CNH VARCHAR(20), 
	PRIMARY KEY(CODMOTORISTA), 
	FOREIGN KEY(CODMOTORISTA) REFERENCES PESSOA(CODPESSOA)
);

-- CIDADE --
CREATE TABLE CIDADE(
	CODCIDADE INT, 
	NOMECIDADE VARCHAR(50), 
	PRIMARY KEY(CODCIDADE)
);

-- ONIBUS --
CREATE TABLE ONIBUS(
	CODONIBUS INT, 
	PLACAONIBUS INT, 
	LUGARESDISPONIVEIS INT, 
	PRIMARY KEY(CODONIBUS)
);		

-- PEDAGIO --
CREATE TABLE PEDAGIO(
	CODPEDAGIO INT,
	RODOVIA VARCHAR(50),
	KM VARCHAR(50),
	LOCALIDADE VARCHAR(50),
	PRECO FLOAT,
	PRIMARY KEY(CODPEDAGIO)
);			

-- ROTA --
CREATE TABLE ROTA(
	CODROTA INT,
	CODMOTORISTA INT, 
	CODONIBUS INT, 
	ORIGEM INT,
	DESTINO INT,
	PRIMARY KEY(CODROTA), 
	FOREIGN KEY(CODMOTORISTA) REFERENCES MOTORISTA(CODMOTORISTA), 
	FOREIGN KEY(CODONIBUS) REFERENCES ONIBUS(CODONIBUS), 
	FOREIGN KEY(ORIGEM) REFERENCES CIDADE(CODCIDADE), 
	FOREIGN KEY(DESTINO) REFERENCES CIDADE(CODCIDADE)
);

-- ROTA/PEDAGIO --
CREATE TABLE ROTA_PEDAGIO(
	CODROTA INT,
	CODPEDAGIO INT,
	PRIMARY KEY(CODROTA, CODPEDAGIO),
	FOREIGN KEY(CODROTA) REFERENCES ROTA(CODROTA),
	FOREIGN KEY(CODPEDAGIO) REFERENCES PEDAGIO(CODPEDAGIO)
);	

-- PASSAGEM --
CREATE TABLE PASSAGEM(
	CODPASSAGEM INT,
	DATAVIAGEM DATE,
    PRECO FLOAT,
    CODROTA INT,
	CODUSU INT,
    PRIMARY KEY(CODPASSAGEM),
    FOREIGN KEY(CODROTA) REFERENCES ROTA(CODROTA),
	FOREIGN KEY(CODUSU) REFERENCES USUARIO(CODUSU)
);
