-- PESSOA --
CREATE TABLE PESSOA(
	CODPESSOA INT, 
	NOMEPESSOA VARCHAR(50), 
	PRIMARY KEY(CODPESSOA)); 

-- USUARIO --
CREATE TABLE USUARIO(CODUSU INT, 
	CPF VARCHAR(20), 
	PRIMARY KEY(CODUSU), 
	FOREIGN KEY(CODUSU) REFERENCES PESSOA(CODPESSOA));

-- MOTORISTA --
CREATE TABLE MOTORISTA(
	CODMOTORISTA INT, 
	CNH VARCHAR(20), 
	PRIMARY KEY(CODMOTORISTA), 
	FOREIGN KEY(CODMOTORISTA) REFERENCES PESSOA(CODPESSOA));

-- CIDADE --
CREATE TABLE CIDADE(
	CODCIDADE INT, 
	NOMECIDADE VARCHAR(50), 
	PRIMARY KEY(CODCIDADE));

-- ONIBUS --
CREATE TABLE ONIBUS(
	CODONIBUS INT, 
	PLACAONIBUS INT, 
	LUGARESDISPONIVEIS INT, 
	PRIMARY KEY(CODONIBUS));																														  

-- PASSAGEM --
CREATE TABLE PASSAGEM(
	CODPASSAGEM INT, 
	DATA DATE, 
	HORA TIME, 
	PRECO FLOAT, 
	CODMOTORISTA INT, 
	CODONIBUS INT, 
	ORIGEM INT, 
	DESTINO INT, 
	PRIMARY KEY(CODPASSAGEM), 
	FOREIGN KEY(CODMOTORISTA) REFERENCES MOTORISTA(CODMOTORISTA), 
	FOREIGN KEY(CODONIBUS) REFERENCES ONIBUS(CODONIBUS), 
	FOREIGN KEY(ORIGEM) REFERENCES CIDADE(CODCIDADE), 
	FOREIGN KEY(DESTINO) REFERENCES CIDADE(CODCIDADE));

-- COMPRA --
CREATE TABLE COMPRA(
	CODCOMPRA INT, 
	CODUSU INT, 
	CODPASSAGEM INT, 
	PRIMARY KEY(CODCOMPRA), 
	FOREIGN KEY(CODUSU) REFERENCES USUARIO(CODUSU), 
	FOREIGN KEY(CODPASSAGEM) REFERENCES PASSAGEM(CODPASSAGEM));
