-- TESTE --
SELECT * FROM PASSAGEM WHERE PASSAGEM.CODROTA = 1;
SELECT * FROM ONIBUS;
SELECT * FROM ONIBUS;

-- INSERIR O 4 NA ROTA 1 NO DIA 12 QUE SO TEM 3 LUGARES --
INSERT INTO PASSAGEM VALUES(9, '12/12/2018', 100, 1, 3);
