-- FUNCAO --
CREATE OR REPLACE FUNCTION CONTROLALUGARES() RETURNS TRIGGER
AS $$
	DECLARE LUGARES INT;
	DECLARE PASSAGENS_COMPRADAS INT;
	BEGIN
		SELECT LUGARESDISPONIVEIS INTO LUGARES FROM ROTA, ONIBUS WHERE
		ROTA.CODROTA = NEW.CODROTA AND
		ONIBUS.CODONIBUS = ROTA.CODONIBUS;
		
		SELECT COUNT(*) INTO PASSAGENS_COMPRADAS FROM PASSAGEM WHERE
		PASSAGEM.DATAVIAGEM = NEW.DATAVIAGEM AND 
		PASSAGEM.CODROTA = NEW.CODROTA;
		
		IF PASSAGENS_COMPRADAS > LUGARES
			THEN RAISE EXCEPTION 'SEM LUGARES DISPONIVEIS PARA HOJE NESSA ROTA';
		END IF;
		RETURN NEW;
	END;
$$ LANGUAGE 'plpgsql';

-- GATILHO --
CREATE TRIGGER CRIAPASSAGEM AFTER UPDATE OR INSERT
ON PASSAGEM FOR EACH ROW
EXECUTE PROCEDURE CONTROLALUGARES();
